// One line per day of the 100-day cycle. Written in-house, in the app's own
// terse "no excuses" voice — deliberately not attributed to real people.
export const MOTIVATIONAL_QUOTES: string[] = [
  "La motivation te fait commencer. La discipline te fait continuer.",
  "Un jour coché ne change rien. Cent jours cochés changent tout.",
  "Tu ne deviens pas discipliné un jour. Tu le deviens chaque jour, un peu plus.",
  "L'excuse la plus convaincante reste une excuse.",
  "Fais-le même sans en avoir envie. Surtout sans en avoir envie.",
  "Chaque case cochée est une preuve, pas une formalité.",
  "Ton futur toi hérite de ce que tu fais aujourd'hui.",
  "Personne ne voit l'effort du jour 47. Toi, si.",
  "La régularité bat l'intensité, presque à chaque fois.",
  "Ce n'est pas le jour parfait qui compte, c'est le jour tenu.",
  "Tu n'as pas besoin d'être inspiré pour être fiable.",
  "Un engagement tenu vaut plus que dix objectifs ambitieux.",
  "Le confort ne construit rien. L'effort répété, si.",
  "Aujourd'hui ne demande qu'une chose : tenir parole.",
  "Ce que tu fais quand c'est facile ne compte pas encore.",
  "La discipline, c'est se respecter avant de se sentir bien.",
  "Un jour manqué se rattrape. Un jour ignoré, jamais.",
  "Tu ne cherches pas la perfection. Tu cherches la continuité.",
  "L'habitude se construit dans les jours ordinaires, pas les grands jours.",
  "Chaque petite victoire d'aujourd'hui finance la grande de demain.",
  "Ne négocie pas avec la version fatiguée de toi-même.",
  "Le jour où tu n'as pas envie est justement celui qui compte le plus.",
  "Tu ne le fais pas pour aujourd'hui. Tu le fais pour qui tu deviens.",
  "La constance est ennuyeuse. C'est pour ça qu'elle marche.",
  "Un système bat une envie, tous les jours de la semaine.",
  "Ce n'est pas une punition. C'est un choix que tu répètes.",
  "Personne ne devient discipliné par accident.",
  "Le doute s'efface après l'action, jamais avant.",
  "Ta série ne se construit pas les bons jours. Elle se construit aujourd'hui.",
  "Fais le minimum plutôt que rien. Zéro casse tout.",
  "Tu n'as pas à te sentir prêt. Tu as juste à commencer.",
  "L'inconfort d'aujourd'hui est la force de demain.",
  "Chaque jour tenu rend le suivant plus facile à tenir.",
  "Ne compte pas les jours restants. Compte les jours tenus.",
  "Ce que tu tolères aujourd'hui, tu le répéteras demain.",
  "La rigueur n'est pas dure. L'abandon l'est, à long terme.",
  "Un pas modeste vaut mieux qu'une intention grandiose.",
  "Tu bâtis une réputation avec toi-même, jour après jour.",
  "L'excellence n'est pas un acte, c'est une habitude répétée.",
  "Le plus dur, c'est de commencer. Alors commence, tout de suite.",
  "Personne ne t'applaudit pour le jour 30. Continue quand même.",
  "Ta discipline d'aujourd'hui est la liberté de demain.",
  "Tenir sa parole envers soi-même, c'est le vrai luxe.",
  "L'échec n'est pas de rater un jour. C'est d'arrêter d'essayer.",
  "Fais ce que tu as dit que tu ferais. Même sans témoin.",
  "Une case cochée à contrecœur compte autant qu'une case cochée avec joie.",
  "Le corps suit la décision, pas l'inverse.",
  "Chaque jour est une nouvelle occasion de prouver que tu tiens parole.",
  "Ce n'est pas une question de talent. C'est une question de présence.",
  "La version de toi que tu admires se construit aujourd'hui, pas un jour.",
  "L'objectif n'est pas de ne jamais douter. C'est d'agir malgré le doute.",
  "Sois ennuyeusement constant. Les résultats ne le seront pas.",
  "Ton cerveau négocie. Ne l'écoute pas, agis.",
  "Un jour à la fois. C'est la seule vitesse qui fonctionne.",
  "La ligne droite n'existe pas. La continuité, si.",
  "Ce que tu fais aujourd'hui compte plus que ce que tu ressens aujourd'hui.",
  "Le respect de soi se gagne dans les détails répétés.",
  "Personne ne vient te motiver à 6h du matin. Fais-le quand même.",
  "Un engagement de 100 jours se tient un jour à la fois, pas d'un coup.",
  "La discipline te libère de la fatigue de décider chaque fois.",
  "Tu n'as pas besoin de te sentir capable. Tu dois juste être présent.",
  "La régularité transforme l'ordinaire en résultat extraordinaire.",
  "Ce jour compte autant que le jour 1. Traite-le pareil.",
  "L'inconstance coûte plus cher que l'effort constant.",
  "Ta parole envers toi-même vaut ce que tu es prêt à tenir.",
  "Rien ne remplace la présence répétée, jour après jour.",
  "Le progrès est silencieux avant d'être visible.",
  "Un jour de moins fatigué ne t'exempte pas d'un jour de plus discipliné.",
  "La discipline n'attend pas l'envie. Elle la précède.",
  "Coche la case. Le sentiment suivra, pas l'inverse.",
  "Ce n'est pas la taille de l'effort qui compte. C'est sa fréquence.",
  "Sois fidèle à toi-même avant d'être fidèle à un résultat.",
  "Un jour ordinaire bien tenu vaut mieux qu'un grand jour isolé.",
  "Le seul jour que tu contrôles, c'est celui-ci.",
  "Tenir, même mal, vaut mieux qu'abandonner proprement.",
  "L'habitude ne demande pas d'énergie. Elle en économise.",
  "Chaque excuse acceptée aujourd'hui en autorise une autre demain.",
  "La discipline est un acte d'amour envers ton futur toi.",
  "Ce que tu répètes devient ce que tu es.",
  "Ne demande pas à te sentir prêt. Demande-toi juste d'être présent.",
  "Le calme vient après l'action, jamais avant.",
  "Un système simple tenu vaut mieux qu'un plan parfait abandonné.",
  "L'exigence envers soi-même ne fatigue pas. Elle construit.",
  "Fais-le pour la personne que tu seras dans 99 jours.",
  "Ce jour ne se rattrapera pas. Il ne repassera pas.",
  "La discipline commence là où l'envie s'arrête.",
  "Personne ne mesure ta valeur à un jour. Ils la mesurent à la série.",
  "Sois précis dans tes efforts, pas seulement ambitieux dans tes intentions.",
  "L'action dissout le doute plus vite que la réflexion.",
  "Un petit progrès tenu bat un grand projet abandonné.",
  "Chaque jour tenu est un vote pour qui tu veux devenir.",
  "La fatigue passe. L'abandon reste.",
  "Tu ne dois rien prouver à personne, sauf à toi-même.",
  "La constance ne brille pas. Elle construit.",
  "Le meilleur moment pour commencer, c'est maintenant, pas demain.",
  "Tiens ta parole aujourd'hui, même en silence.",
  "Ce que tu construis aujourd'hui, tu le récoltes plus tard.",
  "La rigueur d'un jour ordinaire vaut plus qu'un miracle attendu.",
  "Tu n'as pas besoin de motivation. Tu as besoin d'un prochain pas.",
  "Jour après jour, tu deviens la preuve de ta propre discipline.",
];

// cycleDay is 1-indexed (jour 1 → 100). Falls back safely for any out-of-range value.
export function getDailyQuote(cycleDay: number): string {
  const count = MOTIVATIONAL_QUOTES.length;
  const index = ((cycleDay - 1) % count + count) % count;
  return MOTIVATIONAL_QUOTES[index];
}
